// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcUI8RnSnXSt4w34JdfbbEGshJVoCusDw',
    appId: '1:920373992222:web:c86933562e74e97b5c470f',
    messagingSenderId: '920373992222',
    projectId: 'flutter-internship-assgn',
    authDomain: 'flutter-internship-assgn.firebaseapp.com',
    storageBucket: 'flutter-internship-assgn.appspot.com',
    measurementId: 'G-H6D2V9CV7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkgJQBMe9yQtB5y-juN3vCrmnx-jgZBL0',
    appId: '1:920373992222:android:90169a4814bddee95c470f',
    messagingSenderId: '920373992222',
    projectId: 'flutter-internship-assgn',
    storageBucket: 'flutter-internship-assgn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJm4wiQ3IFi2KIm5QmJqigG6OZhzb51i4',
    appId: '1:920373992222:ios:fdf4be9821c4166f5c470f',
    messagingSenderId: '920373992222',
    projectId: 'flutter-internship-assgn',
    storageBucket: 'flutter-internship-assgn.appspot.com',
    iosBundleId: 'com.example.flutterInternshipAssignment',
  );
}
